procodingtips/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
	url(r'^$', views.index),
	url(r'^tips/', include('tips.urls')),
    url(r'^resources/', include('resources.urls')),
    url(r'^admin/', admin.site.urls)
]

urlpatterns += staticfiles_urlpatterns()

resources/urls.py
from django.conf.urls import url

from . import views

app_name = 'resources'
urlpatterns = [
	url(r'^$', views.all_resources_and_groups, name="index"),
	url(r'^groups/$', views.all_groups, name="groups"),
	url(r'^groups/(?P<group_id>[0-9]+)', views.group_detail, name='group_detail'),
]

tips/urls.py
from django.conf.urls import url

from . import views

app_name = 'tips'
urlpatterns = [
	url(r'^$', views.all_tip_list, name="all-tips"),
	url(r'^series/$', views.all_series_list, name="series"),
	url(r'^tips/', views.all_tip_list, name="tips"),
	url(r'^series/(?P<pk>[0-9]+)/', views.all_tips_in_series, name='series_detail'),
	url(r'^likes/', views.like, name='like'),
	url(r'^dislikes/', views.dislike, name='dislikes'),
	url(r'^sort-resources/', views.sort_resources, name='sort-resources'),
]

resources/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Group(models.Model):
	name = models.CharField(max_length=30, unique=True)

	def __str__(self):
		return self.name

class Resource(models.Model):
	name = models.CharField(max_length=30)
	link = models.URLField()
	description = models.TextField()
	group = models.ForeignKey(Group)

	def __str__(self):
		return self.name

tips/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Series(models.Model):
	name = models.CharField(max_length=30)

	def __str__(self):
		return self.name

class Tip(models.Model):
	title = models.CharField(max_length=30)
	author = models.CharField(max_length=30, default="")
	resources = models.TextField(default="")
	body = models.TextField()
	pub_date = models.DateField()
	likes = models.IntegerField(default=0)
	dislikes = models.IntegerField(default=0)
	order = models.IntegerField(default=1)
	series = models.ForeignKey(Series)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ['order']

procodingtips/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'home.html')

resources/views.py
from django.shortcuts import get_object_or_404, render

from .models import Group, Resource

# Create your views here.
def all_resources_and_groups(request):
	groups = Group.objects.all()
	resources = []
	if len(groups) > 0:
		hasGroups = True
		for group in groups:
			currentGroup = Group.objects.get(name=group)
			resources.append(Resource.objects.filter(group=group))
	else:
		hasGroups = False
	context = {
		'groups': groups, 
		'resources': resources,
		'hasGroups': hasGroups,
	}
	return render(request, 'resources/all_resources_and_groups.html', context)

def all_groups(request):
	groups = Group.objects.all()
	return render(request, 'resources/all_groups.html', { 'groups': groups })

def group_detail(request, group_id):
	group = get_object_or_404(Group, pk=group_id)
	resources = Resource.objects.filter(group=group)
	return render(request, 'resources/group_detail.html', { 'group': group, 'resources': resources })

tips/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
import json

from .models import Series, Tip

def sort_resources(request):
	if request.method == 'POST':
		tipTitle = request.POST.get('tip', None)
		tip = get_object_or_404(Tip, title=tipTitle)
		tipID = tip.pk

		resources = {}
		currentResources = tip.resources.replace(', ', ' ')
		resource = []
		previousIndex = 0
		for index in range(0, len(currentResources)):
			char = currentResources[index]
			if " " == char:
				resource.append(currentResources[previousIndex:index])
				previousIndex = index + 1
			elif index == len(currentResources) - 1:
				resource.append(currentResources[previousIndex:])

		for i in range(0, len(resource)):
			resources[i] = resource[i]

		ctx = { 'resources': resources, 'id': tipID }

		return HttpResponse(json.dumps(ctx), content_type='application/json')
	else:
		return HttpResponse("No Data.")

def like(request):
	if request.method == 'POST':
		tipID = request.POST.get('id', None)
		tip = get_object_or_404(Tip, pk=tipID)
		tip.likes += 1
		tip.save()

		ctx  = {'likes': tip.likes, 'id': tipID}
		return HttpResponse(json.dumps(ctx), content_type='application/json')
	else:
		return HttpResponse("No Data.")

def dislike(request):
	if request.method == 'POST':
		tipID = request.POST.get('id', None)
		tip = get_object_or_404(Tip, pk=tipID)
		tip.dislikes += 1
		tip.save()

		ctx  = {'dislikes': tip.dislikes, 'id': tipID}
		return HttpResponse(json.dumps(ctx), content_type='application/json')
	else:
		return HttpResponse("No Data.")

# Create your views here.
def all_series_list(request):
	series = Series.objects.all()
	return render(request, 'tips/series_list.html', { 'series': series })

def all_tip_list(request):
	tips = Tip.objects.all().order_by('-pub_date')
	series_length = len(tips)
	return render(request, 'tips/tip_list.html', { 'tips': tips, 'series_length': series_length })

def all_tips_in_series(request, pk):
	series = get_object_or_404(Series, pk=pk)
	tips = Tip.objects.filter(series=series).order_by('-pub_date')
	series_length = len(tips)
	context = {
		'series': series,
		'tips': tips,
		'series_length': series_length
	}
	return render(request, 'tips/all_tips_in_series.html', context)

resources/templates/resources/all_groups.html
{% extends "layout.html" %}

{% block title %}
	All Groups
{% endblock title %}

{% block body %}
	{% include "navbar.html" with home="" tips="" resources="active" %}

	<div class="container">	
		<ul class="list-unstyled">
	  		<li><h2>All Resource Groups</h2>
	    		<ul>
	    			{% for group in groups %}
	      			<h4><a href="{% url 'resources:group_detail' group.id %}"><li>{{ group.name }}</li></a></h4>
	    			{% endfor %}
	    		</ul>
	  		</li>
	  	</ul>
  	</div>

{% endblock body %}

resources/templates/resources/all_resources_and_groups.html
{% extends "layout.html" %}

{% block title %}
	Groups and Resources
{% endblock title %}

{% block body %}
	{% include "navbar.html" with home="" tips="" resources="active" %}

	<div class="container">
	<h2>All Resource and Groups</h2>
		{% for group in groups %}
			<ul class="list-unstyled">
				<h2><a href="{% url 'resources:group_detail' group.id %}">{{ group.name }}:</a></h2>
				{% for resource in resources %}
				<ul>
					{% for r in resource %}
						{% if group == r.group %}
							<li><a href="{{ r.link }}"><h4>{{ r.name }}</h4></a></li>
							<tiny>{{ r.description }}</tiny>
						{% endif %}
					{% endfor %}
				</ul>
				{% endfor %}
			</ul>
		{% endfor %}
	</div>
{% endblock body %}

resources/templates/resources/group_detail.html
{% extends "layout.html" %}

{% block title %}
	{{group.name}} Resources 
{% endblock title %}

{% block body %}
	{% include "navbar.html" with home="" tips="" resources="active" %}

	<div class="container">	
		<ul class="list-unstyled">
	  		<li><h2>{{ group.name }}</h2>
	    		<ul>
	    			{% for r in resources %}
	      				<h4><a href="{{ r.link }}"><li>{{ r.name }}</li></a></h4>
						<tiny>{{ r.description }}</tiny>
	    			{% endfor %}
	    		</ul>
	  		</li>
	  	</ul>
  	</div>
{% endblock body %}

templates/home.html
{% extends "layout.html" %}

{% block title %}
	Pro Coding Tips
{% endblock title %}

{% block body %}
	{% include "navbar.html" with home="active" %}
	<div class="container">
		<img src="http://logos.cs.uic.edu/reed/Wordle%20Computer%20Science.jpg" alt="Coding" class="img-responsive center-block">
		<br />
		<div class="row">
			<h3 class="col-xs-12 text-center">Curiosity == Knowledge</h3>
		</div>
		<div class="row">
			<h4 class="col-xs-12">
				Pro Coding Tips is a project that aims to help developers with getting started on coding while assisting them with challenges they may face throughout their own experience.
			</h4>
		</div>
		<a href="{% url 'tips:all-tips' %}" class="btn btn-block btn-primary">Read Some Tips</a>
	</div>
	<div class="footer" style="margin-top: 30px;"></div>
{% endblock body %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://bootswatch.com/paper/bootstrap.min.css" />
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" />
		<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
		<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
		<link rel="icon" type="image/png" href="/favicon-194x194.png" sizes="194x194">
		<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
		<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
		<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
		<link rel="manifest" href="/manifest.json">
		<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#303f9f">
		<meta name="msapplication-TileColor" content="#303f9f">
		<meta name="msapplication-TileImage" content="/mstile-144x144.png">
		<meta name="theme-color" content="#ffffff">
		<title>{% block title %}{% endblock title %}</title>
	</head>

	<body>
		{% block body %}{% endblock body %}
	</body>

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</html>

templates/navbar.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
      <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Pro Coding Tips</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{{ home|default:'' }}"><a href="#">Home <span class="sr-only">(current)</span></a></li>
                <li class="{{ tips|default:'' }} dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tips <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url 'tips:series' %}">Series</a></li>
                        <li><a href="{% url 'tips:all-tips' %}">All Tips</a></li>
                    </ul>
                </li>
                <li class="{{ resources|default:'' }} dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Resources <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url 'resources:index' %}">Resources and Groups</a></li>
                        <li><a href="{% url 'resources:groups' %}">All Groups</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

tips/templates/tips/all_tips_in_series.html
{% extends "layout.html" %}

{% block title %}
	{{ series.name }} Tips
{% endblock title %}

{% block body %}
	{% include "navbar.html" with home="" tips="active" resources="" %}

	<div class="container">
		<h2>Series: {{ series.name }}</h2>
		{% for t in tip %}
			<bold><h2>{{ t.title }}</h2></bold>
			<h5 style="color: gray;">By: {{ t.author }}</h5>
			<h4>Tip {{ t.order }} of {{ series_length }} of Series {{ t.series.name }}</h4>
			<h4>
			<div style="position: relative">
				<div class="dropdown">
					<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
				    	Resources
				    	<span class="caret"></span>
				  	</button>
				  	<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				    	<li>{{ t.resources }}</li>
				  	</ul>
				</div>
			</div>
			</h4>
			<br>
			<p>{{ t.body }}</p>
			</br>
			<div class="row">
				<div class="col-xs-6">
					<h4>Posted on: {{ t.pub_date }}</h4>
				</div>
				<div class="col-xs-6">
					<h4>Likes: {{ t.likes }} Dislikes:{{ t.dislikes }}</h4>
				</div>
			</div>
		{% endfor %}
	</div>




{% endblock body %}

tips/templates/tips/series_list.html
{% extends "layout.html" %}

{% block title %}
	All Tip Series
{% endblock title %}

{% block body %}
	{% include "navbar.html" with home="" tips="active" resources="" %}
	
	<div class="container">
		<ul class="list-unstyled">
	  		<li><h2>All Series</h2>
	    		<ul>
	    			{% for s in series %}
	      				<h4><a href="{% url 'tips:series_detail' s.id %}"><li>{{ s.name }}</li></a></h4>
	    			{% endfor %}
	    		</ul>
	  		</li>
	  	</ul>
	</div>
{% endblock body %}

tips/templates/tips/tip_list.html
{% extends "layout.html" %}

{% block title %}
	All Tips
{% endblock title %}

{% block body %}
	{% include "navbar.html" with home="" tips="active" resources="" %}
	{% for tip in tips %}
	
	<div class="container">
		<bold><h2>{{ tip.title }}</h2></bold>
		<h5 style="color: gray;">By: {{ tip.author }}</h5>
		<h4>Tip {{ tip.order }} of {{ series_length }} of Series {{ tip.series.name }}</h4>
		<h4>
		<div style="position: relative">
			<div class="dropdown">
				<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
			    	Resources
			    	<span class="caret"></span>
			  	</button>
			  	<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
			    	<li>{{ tip.resources }}</li>
			  	</ul>
			</div>
		</div>
		</h4>
		<br>
		<p>{{ tip.body }}</p>
		</br>
		<div class="row">
			<div class="col-xs-6">
				<h4>Posted on: {{ tip.pub_date }}</h4>
			</div>
			<div class="col-xs-6">
				<h4>Likes: {{ tip.likes }} Dislikes:{{ tip.dislikes }}</h4>
			</div>
		</div>
	</div>


		
		
	{% endfor %}
{% endblock body %}

tips/templates/tips/tips_outline.html
{% for tip in tips %}
	<bold><h2 class="title">{{ tip.title }}</h2></bold>
	<h5 style="color: gray;">By: {{ tip.author }}</h5>
	<h4>Tip {{ tip.order }} of {{ series_length }} in Series {{ tip.series.name }}</h4>
	<div class="row">
		<div class="col-xs-12 col-md-3">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Resources Used:</h3>
				</div>
				<div class="panel-body">
					<ul class="resources-{{ tip.id }}">
					</ul>
				</div>
			</div>
		</div>
	</div>
	<p>{{ tip.body|safe }}</p>
	<h5>Post on: {{ tip.pub_date }}</h5>
	<h5>
		<span class="likes-span-{{ tip.id }}">{{ tip.likes }}</span>
		&nbsp;<span class="glyphicon glyphicon-thumbs-up like" name="{{ tip.id }}"></span>
		<span class="dislikes-span-{{ tip.id }}">{{ tip.dislikes }}</span>
		&nbsp;<span class="glyphicon glyphicon-thumbs-down dislikes" name="{{ tip.id }}"></span>
	</h5>
{% endfor %}

<script>
	function getResources() {
		var tips = [];
		$('.title').each((i, obj) => {
			var tipTitle = obj.textContent;
			tips.push(tipTitle);
		});

		for (var i in tips) {
			var tip = tips[i];
			$.ajax({
					type: 'POST',
					url: '/tips/sort-resources/',
					data: {'tip': tip, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
					dataType: 'json',
					success: function(response) {
						var id = response['id'];
						var resources = response['resources'];
						for (var i in resources) {
							var resource = resources[i];
							$(`.resources-${id}`).append(`<li><h5>${resource}</h5></li>`);
						}
					},
					error: (rs, e) => {
						console.log(rs);
					}
			})
		}
	}
</script>
<script>
	$(document).ready(function() {
		getResources();

		$('.like').click(function() {
			$.ajax({
				type: 'POST',
				url: "/tips/likes/",
				data: {'id': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
				dataType: 'json',
				success: function(response) {
					var likes = response['likes'];
					var id = response['id'];
					$('.likes-span-' + id).text(likes);
				},
				error: function(rs, e) {
					console.error(rs);
				}
			});
		});

		$('.dislikes').click(function() {
			$.ajax({
				type: 'POST',
				url: "/tips/dislikes/",
				data: {'id': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
				dataType: 'json',
				success: function(response) {
					var dislikes = response['dislikes'];
					var id = response['id'];
					$('.dislikes-span-' + id).text(dislikes);
				},
				error: function(rs, e) {
					console.error(rs);
				}
			});
		});
	});
</script>